Import library

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [33]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [34]:
print(X)
print(y)

[[2141.       2154.       2121.350098 2131.550049 2124.715088]
 [2120.       2123.899902 2088.       2097.050049 2090.325684]
 [2118.       2122.       2077.       2081.850098 2075.174316]
 ...
 [2149.350098 2203.       2128.149902 2173.5      2173.5     ]
 [2168.850098 2185.199951 2147.850098 2164.25     2164.25    ]
 [2174.       2186.800049 2152.600098 2172.649902 2172.649902]]
[15731396 10401212 11667129 15098991  8947563 27630190 12961252 12537520
 28648125 17821397 12437162  8577634 13141644 10119064 12643749 25525961
 64750460 27445768 20335273 12542824 15668979 11919927 15264068 15519031
 16056620 19839282 13764841 13095028  9076248 11926328 11290667  9591456
  8732869  8497216 24538346  9727405  8558745  6565515 10666190 12341434
  9246702  9960828 14398973  8529573 15728986 14215215 10809307 17225212
 16835005 13809929 14147418 15700946 45857806 40931170 37003111 17170274
 30770080 16539467 17045147 26178477 18481466 20946864 21479385 14030652
 12828008 26522972 20918665 1427

In [46]:
y = y.reshape(len(y), 1)
y

array([[15731396],
       [10401212],
       [11667129],
       [15098991],
       [ 8947563],
       [27630190],
       [12961252],
       [12537520],
       [28648125],
       [17821397],
       [12437162],
       [ 8577634],
       [13141644],
       [10119064],
       [12643749],
       [25525961],
       [64750460],
       [27445768],
       [20335273],
       [12542824],
       [15668979],
       [11919927],
       [15264068],
       [15519031],
       [16056620],
       [19839282],
       [13764841],
       [13095028],
       [ 9076248],
       [11926328],
       [11290667],
       [ 9591456],
       [ 8732869],
       [ 8497216],
       [24538346],
       [ 9727405],
       [ 8558745],
       [ 6565515],
       [10666190],
       [12341434],
       [ 9246702],
       [ 9960828],
       [14398973],
       [ 8529573],
       [15728986],
       [14215215],
       [10809307],
       [17225212],
       [16835005],
       [13809929],
       [14147418],
       [15700946],
       [4585

Splitting Dataset into Train and Test

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
X_train = sc_x.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

Training the SVR model on the training set

In [43]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting the test set results

In [44]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.rehape(len(y_test), 1))))

ValueError: ignored

Evaluating the model performance

In [45]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

NameError: ignored